spring.application.name=qr-code-generator
server.port=8090

# H2 in-memory database
spring.datasource.url=jdbc:h2:mem:qrdb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop

# H2 console (acessível em /h2-console durante desenvolvimento)
spring.h2.console.enabled=true
